In [1]:
from numpy import *

In [2]:
def carrés(n):
    """
    :entrée n: int
    :pré-cond: n > 0
    :sortie a: tableau de int
    :post-cond: a contient les  n premiers carrés parfaits (en commençant par 0),
                c’est à dire :
                len(a) = n; ∀i ∈ [0; len(a)[, a[i] = i²
    """
    a = empty(n, int)
    i = 0
    while i < len(a):
        a[i] = i*i
        i = i+1
    return a
    
print( carrés(10) )

[ 0  1  4  9 16 25 36 49 64 81]


In [3]:
def inverse(a):
    """
    :entrée a: tableau de float
    :pré-cond: ∅
    :sortie ai: tableau de float
    :post-cond: ai contient les mêmes éléments que a, en ordre inverse,
                c’est à dire
                len(ai) = len(a); ∀i ∈ [0; len(a)[, ai[i] = a[len(a)-1-i]
    """
    ai = empty(len(a), float)
    i = 0
    while i < len(ai):
        ai[i] = a[len(a)-1-i]
        i = i+1
    return ai

def inverse(a):
    """
    :entrée a: tableau de float
    :pré-cond: ∅
    :sortie ai: tableau de float
    :post-cond: ai contient les mêmes éléments que a, en ordre inverse,
                c’est à dire
                len(ai) = len(a); ∀i ∈ [0; len(a)[, ai[i] = a[len(a)-1-i]
    """
    ai = empty(len(a), float)
    i = 0
    j = len(a)-1
    while i < len(ai):
        ai[i] = a[j]
        i = i+1
        j = j-1
    return ai
    
test = array([1.0, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0])
print( inverse(test) )


[13.  8.  5.  3.  2.  1.  1.]


In [4]:
def filtre(a, v):
    """
    :entrée a: tableau de float
    :entrée v: float
    :pré-cond: ∅
    :sortie af: tableau de float
    :post-cond: af contient tous les éléments de a inférieurs ou égaux à v,
                et uniquement eux, dans le même ordre que dans a
                (on a donc filtré tous les éléments supérieurs à v)
    """
    
    taille_af = 0
    i = 0
    while i < len(a):
        if a[i] <= v:
            taille_af = taille_af+1
        i = i+1
    af = empty(taille_af, float)
    j = 0 # indice du tableau af
    i = 0 # indice du tableau a
    while i < len(a):
        if a[i] <= v:
            af[j] = a[i]
            j = j+1
        i = i+1
    return af
        
        
test = array([1.0, 3.0, 5.0, 2.0, 4.0, 6.0])
print( filtre(test, 4.0) )
print(test)

[1. 3. 2. 4.]
[1. 3. 5. 2. 4. 6.]


In [5]:
def inverse_en_place(a):
    """
    :entrée/sortie a: tableau de float
    :pré-cond: ∅
    :post-cond: aₛ contient les mêmes éléments que aₑ, en ordre inverse,
                c’est à dire
                ∀i ∈ [0; len(aₑ)[, aₛ[i] = aₑ[len(aₑ)-1-i]
    """
    i = 0
    j = len(a)-1
    while i < j:
        tmp = a[i]
        a[i] = a[j]
        a[j]= tmp
        i = i+1
        j = j-1
    
test = array([1.0, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0])
inverse_en_place(test)
print(test)

[13.  8.  5.  3.  2.  1.  1.]
