In [1]:
from numpy import array

a = array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [2]:
b = a[1:]
print(b)

[20 30 40 50]


In [3]:
b[0] = 99
print(b)

[99 30 40 50]


In [4]:
print(a)

[10 99 30 40 50]


In [5]:
def indice_min(a):
    if len(a) == 1:
        return 0
    else:
        i = indice_min(a[1:])+1
        if a[0] <= a[i]:
            return 0
        else:
            return i
            
def tri_sel(a):
    if len(a) <= 1:
        pass # rien à faire
    else:
        imin = indice_min(a)
        tmp = a[0]
        a[0] = a[imin]
        a[imin] = tmp
        tri_sel(a[1:])
    
def tri_sel(a):
    b = a
    while len(b) >= 1:
        imin = indice_min(b)
        tmp = b[0]
        b[0] = b[imin]
        b[imin] = tmp
        b = b[1:]
    
A = array([3,6,1,4,9,2,4])
tri_sel(A)
print(A)

[1 2 3 4 4 6 9]


In [6]:
def insere_gauche(a, i):
    """
    :entrée/sortie a: tableau de float
    :entrée i: int
    :pré-cond: 0 ≤ i < len(a)
               a est trié entre les indices 0 et i-1 inclus
    :post-cond: a est trié entre les indices 0 et i
                les cases d'indice > i n'ont pas été modifiées
    """
    while i > 0 and a[i-1] > a[i]:
        tmp = a[i]
        a[i] = a[i-1]
        a[i-1] = tmp
        i = i-1
        
def insere_gauche(a, i):
    if i == 0 or a[i-1] <= a[i]:
        pass
    else:
        tmp = a[i]
        a[i] = a[i-1]
        a[i-1] = tmp
        insere_gauche(a, i-1)
  
        
a = [2,5,8,4,3]
insere_gauche(a, 3)
print(a)

[2, 4, 5, 8, 3]


In [7]:
a = [2,5,8,1,3]
insere_gauche(a, 3)
print(a)

[1, 2, 5, 8, 3]
